import { img } from "@/content/innerPageData";

export type LibraryBook = {
  id: string;
  title: string;
  author: string;
  year: string;
  pages?: string;
  isbn?: string;
  copies?: number;
  edition?: string;
  publisher?: string;
  category: string;
  callNumber: string;
  availability: "On shelf" | "Issued" | "Reference only";
  location: string;
  summary: string;
  tags: string[];
  color: string;
  accent: string;
  height: number;
  width: number;
  tilt?: number;
};

const book = (entry: LibraryBook) => entry;

export const library = {
  title: "Library",
  heroImage: img("photo-1521587760476-6c12a4b040da"),
  heroLead: "Prints, journals, e-resources and a quiet room to work in.",
  kicker: "Library",
  heading: "A room built for reading, and a collection built for the syllabus.",
  lead: "The college library holds textbooks for every paper, reference books, journals and e-resources. It also provides a quiet reading section where students can work without being interrupted.",
  intro: [
    {
      title: "Syllabus-first collection",
      text: "Every paper in every programme has at least one supporting text, with additional reference titles for deeper reading.",
    },
    {
      title: "Journals and e-resources",
      text: "Current journals and online databases support assignments, projects and competitive examination preparation.",
    },
    {
      title: "Quiet study space",
      text: "A dedicated reading section, open through study hours, where long sessions of work are possible.",
    },
  ],
  shelfNote:
    "A shelf is only a starting point. Choose any spine to pull the book out, open it and read what it is about.",
  collection: [
    "Textbooks",
    "Reference books",
    "Journals",
    "E-resources",
    "Quiet reading section",
    "Campus internet",
  ],
  howTo: {
    kicker: "Using the library",
    title: "Get more from the collection",
    items: [
      {
        title: "Start with the reference shelf",
        text: "Reference titles summarise a topic in a fraction of the time. Use them before committing to a full textbook.",
      },
      {
        title: "Read one journal a month",
        text: "Regular journal reading builds the writing habit that assignments and examinations eventually require.",
      },
      {
        title: "Cite what you use",
        text: "Learn referencing early. Project work that cites sources properly scores better and takes less time to write.",
      },
    ],
  },
  row: {
    id: "reading-room",
    title: "The Library Collection",
    label: "Reading room",
    books: [
      book({
        id: "financial-accounting-bcom-bba",
        title: "Financial Accounting for B.Com, BBA and Foundation Courses",
        author: "S. N. Maheshwari, S. K. Maheshwari & Sharad K. Maheshwari",
        year: "2024",
        edition: "8th edition",
        publisher: "Vikas Publishing",
        isbn: "9789359303222",
        category: "Accounting",
        copies: 12,
        callNumber: "657.2 MAH/FIN",
        availability: "On shelf",
        location: "Aisle A · Bay 1",
        summary:
          "The standard undergraduate accounting text written for B.Com and BBA students, covering the full accounting cycle from journalising transactions through to partnership accounts.",
        tags: ["Textbook", "B.Com", "BBA"],
        color: "#1f3a5f",
        accent: "#d8c48a",
        height: 266,
        width: 66,
      }),
      book({
        id: "advanced-accountancy-vol-1",
        title: "Advanced Accountancy, Volume I",
        author: "S. N. Maheshwari, S. K. Maheshwari & Sharad K. Maheshwari",
        year: "2023",
        edition: "12th edition",
        publisher: "Vikas Publishing",
        isbn: "9789356746312",
        category: "Accounting",
        copies: 9,
        callNumber: "657.2 MAH/ADV/1",
        availability: "On shelf",
        location: "Aisle A · Bay 2",
        summary:
          "First half of the two-volume advanced accountancy course, dealing with the treatment of corporate accounts and the reporting of financial statements.",
        tags: ["Textbook", "B.Com"],
        color: "#2d4a3e",
        accent: "#e4d3a1",
        height: 264,
        width: 58,
      }),
      book({
        id: "advanced-accountancy-vol-2",
        title: "Advanced Accountancy, Volume II",
        author: "S. N. Maheshwari, S. K. Maheshwari & Sharad K. Maheshwari",
        year: "2023",
        edition: "12th edition",
        publisher: "Vikas Publishing",
        isbn: "9789356746329",
        category: "Accounting",
        copies: 8,
        callNumber: "657.2 MAH/ADV/2",
        availability: "Issued",
        location: "Aisle A · Bay 2",
        summary:
          "Second volume of the advanced accountancy course, covering consolidation of accounts, holding company finance and related advanced topics.",
        tags: ["Textbook", "B.Com"],
        color: "#5a2d3a",
        accent: "#e9d5b0",
        height: 264,
        width: 58,
      }),
      book({
        id: "corporate-accounting",
        title: "Corporate Accounting",
        author: "S. N. Maheshwari, S. K. Maheshwari & Sharad K. Maheshwari",
        year: "2022",
        edition: "6th edition",
        pages: "1,432 pp.",
        publisher: "Vikas Publishing",
        isbn: "9789354535000",
        category: "Accounting",
        copies: 6,
        callNumber: "657.2 MAH/COR",
        availability: "On shelf",
        location: "Aisle A · Bay 3",
        summary:
          "A long-standing reference on accounting for different forms of corporate body, kept in step with the growing complexity of corporate reporting.",
        tags: ["Reference", "Accounting"],
        color: "#3a2f52",
        accent: "#dcc79a",
        height: 270,
        width: 66,
      }),
      book({
        id: "cost-accounting-principles-practice",
        title: "Cost Accounting: Principles and Practice",
        author: "S. P. Jain & K. L. Narang",
        year: "2022",
        edition: "13th edition",
        publisher: "Vikas Publishing",
        isbn: "9789354530265",
        category: "Cost Accounting",
        copies: 7,
        callNumber: "657.3 JAI/COS",
        availability: "On shelf",
        location: "Aisle A · Bay 4",
        summary:
          "Builds the grounding in cost concepts, cost behaviour and costing methods that commerce students need before moving on to cost analysis and decision making.",
        tags: ["Textbook", "B.Com", "BBA"],
        color: "#6b4a1f",
        accent: "#f0dcaa",
        height: 258,
        width: 58,
      }),
      book({
        id: "income-tax-law-and-practice",
        title: "Income Tax Law and Practice",
        author: "Dr H. C. Mehrotra & Dr S. P. Goyal",
        year: "2020",
        edition: "61st edition",
        pages: "645 pp.",
        publisher: "Sahitya Bhawan Publications",
        isbn: "9789351734345",
        category: "Taxation",
        copies: 10,
        callNumber: "343.54 MEH/INC",
        availability: "On shelf",
        location: "Aisle B · Bay 1",
        summary:
          "Published since 1964 and revised each assessment year, this is the most widely used income tax text for B.Com students in Kerala and across India.",
        tags: ["Textbook", "B.Com", "Reference"],
        color: "#4a2a2a",
        accent: "#e3c9a0",
        height: 256,
        width: 56,
      }),
      book({
        id: "financial-management-pandey",
        title: "Financial Management",
        author: "I. M. Pandey",
        year: "2015",
        edition: "11th edition",
        pages: "921 pp.",
        publisher: "Vikas Publishing",
        isbn: "9789325982291",
        category: "Finance",
        copies: 6,
        callNumber: "658.15 PAN/FIN",
        availability: "On shelf",
        location: "Aisle B · Bay 2",
        summary:
          "Takes an analytical approach to corporate finance decisions, covering investment, financing and dividend policy in a single comprehensive volume.",
        tags: ["Textbook", "BBA", "Finance"],
        color: "#1d4a4a",
        accent: "#d9cfa4",
        height: 260,
        width: 60,
      }),
      book({
        id: "principles-of-management-accounting",
        title: "Principles of Management Accounting",
        author: "S. N. Maheshwari, S. K. Maheshwari & Sharad K. Maheshwari",
        year: "2021",
        edition: "18th revised edition",
        pages: "756 pp.",
        publisher: "Sultan Chand & Sons",
        isbn: "9789351611783",
        category: "Management",
        copies: 5,
        callNumber: "658.15 MAH/MGT",
        availability: "On shelf",
        location: "Aisle B · Bay 3",
        summary:
          "Links management accounting to decision making, with worked treatment of cost behaviour, absorption costing, budgeting, standard costing and variance analysis.",
        tags: ["Textbook", "B.Com", "BBA"],
        color: "#4b3d1f",
        accent: "#e8d5a6",
        height: 256,
        width: 56,
      }),
      book({
        id: "fundamentals-of-mathematical-statistics",
        title: "Fundamentals of Mathematical Statistics",
        author: "S. C. Gupta & V. K. Kapoor",
        year: "2020",
        edition: "12th revised edition",
        publisher: "Sultan Chand & Sons",
        isbn: "9789351611738",
        category: "Statistics",
        copies: 8,
        callNumber: "519.5 GUP/FUN",
        availability: "On shelf",
        location: "Aisle B · Bay 4",
        summary:
          "The standard statistics reference for commerce and management students, covering distribution theory, estimation and hypothesis testing with solved problems.",
        tags: ["Textbook", "B.Com", "BBA"],
        color: "#243f5e",
        accent: "#d9c79b",
        height: 254,
        width: 54,
      }),
      book({
        id: "problems-solutions-advanced-financial-accounting",
        title: "Problems and Solutions in Advanced Financial Accounting",
        author: "S. P. Jain & K. L. Narang",
        year: "2017",
        publisher: "Kalyani Publishers",
        isbn: "9789327275674",
        category: "Accounting",
        copies: 11,
        callNumber: "657.2 JAI/PRO",
        availability: "On shelf",
        location: "Aisle A · Bay 5",
        summary:
          "A problem book written to the Kerala University B.Com fifth semester pattern, with solved and unsolved questions for practice and revision.",
        tags: ["Practice", "Kerala University", "B.Com"],
        color: "#5c1f2e",
        accent: "#eed7ab",
        height: 250,
        width: 52,
      }),
      book({
        id: "data-structures-using-c",
        title: "Data Structures Using C",
        author: "Reema Thareja",
        year: "2014",
        edition: "2nd edition",
        pages: "531 pp.",
        publisher: "Oxford University Press",
        isbn: "9780198099307",
        category: "Computer Science",
        copies: 9,
        callNumber: "005.73 THA/DAT",
        availability: "On shelf",
        location: "Aisle C · Bay 1",
        summary:
          "A core data structures text for undergraduate computer applications, linking abstract concepts to their C implementations with worked exercises.",
        tags: ["Textbook", "B.Com Computer Application"],
        color: "#2b3f52",
        accent: "#d6c79c",
        height: 258,
        width: 54,
      }),
      book({
        id: "programming-in-ansi-c",
        title: "Programming in ANSI C",
        author: "E. Balagurusamy",
        year: "2024",
        edition: "9th edition",
        publisher: "McGraw Hill India",
        isbn: "9789355326720",
        category: "Computer Science",
        copies: 7,
        callNumber: "005.74 BAL/PRO",
        availability: "On shelf",
        location: "Aisle C · Bay 2",
        summary:
          "The long-running C programming text used across Indian universities, introducing the language from fundamentals through to structured and object oriented programming.",
        tags: ["Textbook", "B.Com Computer Application"],
        color: "#1f4438",
        accent: "#dcd0a2",
        height: 256,
        width: 54,
      }),
      book({
        id: "train-to-pakistan",
        title: "Train to Pakistan",
        author: "Khushwant Singh",
        year: "2023",
        pages: "192 pp.",
        publisher: "Penguin India",
        isbn: "9780670098163",
        category: "Indian Writing",
        copies: 6,
        callNumber: "823.914 SIN/TRA",
        availability: "Issued",
        location: "Aisle D · Bay 1",
        summary:
          "Partition reaches the village of Mano Majra in the form of a ghost train, and a love story between a Sikh boy and a Muslim girl plays out against the violence.",
        tags: ["Indian writing", "Classic"],
        color: "#6d2f2f",
        accent: "#f0d6a6",
        height: 244,
        width: 42,
      }),
      book({
        id: "sapiens",
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        year: "2015",
        pages: "512 pp.",
        publisher: "Penguin India",
        isbn: "9780099590088",
        category: "General Reading",
        copies: 4,
        callNumber: "909 HAR/SAP",
        availability: "On shelf",
        location: "Aisle D · Bay 2",
        summary:
          "A sweeping account of how an unremarkable ape came to dominate the planet, tracing the shared fictions that let very large societies cohere.",
        tags: ["General reading", "History"],
        color: "#3a4756",
        accent: "#e2d3a8",
        height: 248,
        width: 46,
      }),
      book({
        id: "things-fall-apart",
        title: "Things Fall Apart",
        author: "Chinua Achebe",
        year: "1994",
        pages: "224 pp.",
        publisher: "Anchor Books",
        isbn: "9780385474542",
        category: "World Literature",
        copies: 5,
        callNumber: "823.914 ACH/THI",
        availability: "On shelf",
        location: "Aisle D · Bay 3",
        summary:
          "Okonkwo's resistance to the arrival of British power in his Igbo community, and the collapse of the world he had built his standing on.",
        tags: ["World literature", "Classic"],
        color: "#1f513f",
        accent: "#e5d5a4",
        height: 242,
        width: 40,
      }),
      book({
        id: "pride-and-prejudice",
        title: "Pride and Prejudice",
        author: "Jane Austen",
        year: "2002",
        pages: "448 pp.",
        publisher: "Penguin Classics",
        isbn: "9780141439518",
        category: "English Literature",
        copies: 8,
        callNumber: "823.912 AUST/PRE",
        availability: "On shelf",
        location: "Aisle D · Bay 4",
        summary:
          "Elizabeth Bennet and Fitzwilliam Darcy misjudge each other for most of a comedy of manners that is still the sharpest thing written about courtship and class.",
        tags: ["Classic", "English literature"],
        color: "#7c2233",
        accent: "#e3c489",
        height: 246,
        width: 44,
      }),
      book({
        id: "jane-eyre",
        title: "Jane Eyre",
        author: "Charlotte Bronte",
        year: "1996",
        publisher: "Penguin Classics",
        isbn: "9780141439341",
        category: "English Literature",
        copies: 7,
        callNumber: "823.912 BRO/JAN",
        availability: "On shelf",
        location: "Aisle D · Bay 5",
        summary:
          "A governess refuses to accept a love that asks her to surrender her own judgement, and leaves Thornfield to find a life on her own terms.",
        tags: ["Classic", "English literature"],
        color: "#2d2a4d",
        accent: "#ddcb9d",
        height: 246,
        width: 44,
      }),
      book({
        id: "wings-of-fire",
        title: "Wings of Fire: An Autobiography",
        author: "A. P. J. Abdul Kalam & Arun Tiwari",
        year: "1999",
        publisher: "Universities Press",
        isbn: "9788173711466",
        category: "Biography",
        copies: 6,
        callNumber: "926.23 KAL/WIN",
        availability: "On shelf",
        location: "Aisle D · Bay 6",
        summary:
          "The former President's own account of growing up in Rameswaram and the decades of work that took India from a bicycle workshop to a space power.",
        tags: ["Biography", "Indian writing"],
        color: "#8a4a1c",
        accent: "#f2d9a8",
        height: 244,
        width: 42,
      }),
    ],
  },
} as const;
